<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    In Java, the "finally" keyword is used in conjunction with try-catch blocks to define a block of code that will be executed regardless of whether an exception is thrown or not. The "finally" block is placed after the "catch" block(s) and is used to specify a set of statements that must be executed before the control flow leaves the try-catch block.
<br>
<br>
The syntax for using the "finally" keyword in Java is as follows: <br>
<code>try { <br>
    // Code that may throw an exception<br>
} catch (ExceptionType1 e1) { <br>
    // Code to handle ExceptionType1 <br>
} catch (ExceptionType2 e2) {<br>
    // Code to handle ExceptionType2<br>
} finally {<br>
    // Code in the finally block <br>
}</code>
<br>
In this example, the "try" block contains the code that may throw an exception. If an exception of type "ExceptionType1" is thrown, it will be caught and handled in the corresponding "catch" block. Similarly, if an exception of type "ExceptionType2" is thrown, it will be caught and handled in the respective "catch" block. Regardless of whether an exception is thrown or not, the code in the "finally" block will be executed before the control flow leaves the try-catch block, allowing for cleanup or other necessary operations.

It's important to note that the "finally" block is optional, and it's not required to have one in every try-catch block. However, if a "finally" block is present, it will be executed even if there is a return statement or an exception thrown in the "try" or "catch" block(s).
  <h3>Why use Java finally block?(H3 tag use karna)</h3> 
  <ol>
    <li>finally block in Java can be used to put "cleanup" code such as closing a file, closing connection, etc.</li>
    <li>The important statements to be printed can be placed in the finally block.</li>
 </ol>
 <h3>Usage of Java finally</h3>
Case 1: When an exception does not occur <br>
class TestFinallyBlock {    <br>
  public static void main(String args[]){  <br>  
  try{    <br>
//below code do not throw any exception  <br>
   int data=25/5;    <br>
   System.out.println(data);<br>    
  }    <br>
//catch won't be executed  <br>
  catch(NullPointerException e){  <br>
System.out.println(e);  <br>
}    <br>
//executed regardless of exception occurred or not  <br>
 finally {  <br>
System.out.println("finally block is always executed"); <br> 
}    <br>
<br>
System.out.println("rest of phe code...");  <br>  
  }    <br>
}    <br>
Output:<br>
<br>
Java finally block<br>
Case 2: When an exception occurr but not handled by the catch block<br>
Let's see the the fillowing example. Here, the code throws an exception however the catch block cannot handle it. Despite this, the finally block is executed after the try block and then the program terminates abnormally.<br>

TestFinallyBlock1.java<br>
<br>
public class TestFinallyBlock1{    <br>
      public static void main(String args[]){   <br>
  
      try {    <br>
        <br>
        System.out.println("Inside the try block");  <br>
        <br>
        //below code throws divide by zero exception  <br>
       int data=25/0;  <br>  
       System.out.println(data);   <br> 
      }    <br>
      //cannot handle Arithmetic type exception  <br>
      //can only accept Null Pointer type exception <br>  
      catch(NullPointerException e){  <br>
        System.out.println(e);  <br>
      }   <br>
      <br>
      //executes regardless of exception occured or not   <br>
      finally { <br> 
        System.out.println("finally block is always executed");  <br>
      }   <br> 
      <br>
      System.out.println("rest of the code...");    <br>
      }    <br>
    }  <br>  
Output:<br>
<br>
Java finally block<br>
Case 3: When an exception occurs and is handled by the catch block<br>
Example:<br>
<br>
Let's see the following example where the Java code throws an exception and the catch block handles the exception. Later the finally block is executed after the try-catch block. Further, the rest of the code is also executed normally.<br>
<br>
TestFinallyBlock2.java<br>
<br>
public class TestFinallyBlock2{ <br>   
      public static void main(String args[]){ <br>  
        <br>
      try { <br>   
        <br>
        System.out.println("Inside try block");  <br>
        <br>
        //below code throws divide by zero exception  <br>
       int data=25/0;    <br>
       System.out.println(data);<br>    
      }   <br>
      <br>
      //handles the Arithmetic Exception / Divide by zero exception <br> 
      catch(ArithmeticException e){  <br>
        System.out.println("Exception handled");  <br>
        System.out.println(e); <br> 
      }  <br> 
      <br>
      //executes regardless of exception occured or not   <br>
      finally {  <br>
        System.out.println("finally block is always executed");  <br>
      }    <br>
      <br>
      System.out.println("rest of the code...");    <br>
      }   <br> 
    }<br>
 
</body>
</html>